image: node:16.19.1
pipelines:
  default:
    - step:
        name: Install Vercel CLI, Pull Vercel Environment Information, Build Project Artifacts and Deploy Project Artifacts to Vercel
        script:
          - npm install --global vercel
          - vercel pull --yes --environment=preview --token=$STG_VERCEL_TOKEN
          - vercel build --token=$STG_VERCEL_TOKEN
          - vercel deploy --prebuilt  --token=$STG_VERCEL_TOKEN
  branches:
    development:
      - step:
          name: Install Vercel CLI, Pull Vercel Environment Information, Build Project Artifacts and Deploy Project Artifacts to Vercel
          script:
            - npm install --global vercel
            - vercel pull --yes --environment=production --token=$STG_VERCEL_TOKEN
            - vercel build --prod --token=$STG_VERCEL_TOKEN
            - vercel deploy --prebuilt --prod --token=$STG_VERCEL_TOKEN
    master:
      - step:
          name: Install Vercel CLI, Pull Vercel Environment Information, Build Project Artifacts and Deploy Project Artifacts to Vercel
          script:
            - npm install --global vercel
            - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
            - vercel build --prod --token=$VERCEL_TOKEN
            - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
